### ISSUE TITLE
Impersonate stopped working after Laravel update?

### ISSUE THREAD

**Issue by seabasss** [stechstudio/filament-impersonate#10] opened 2022-03-29 22:29 UTC
Impersonate stopped working after I updated Laravel. I was on Laravel 9.3.1 and it worked and after updating to 9.6.0 I just get logged out when I click on the impersonate button. Any ideas why? Impersonate, Filament and Jetstream are all on latest versions.

I found two things that seems to "fix" this. One is removing this line from `App\Http\Kernel.php` ... ```\Laravel\Jetstream\Http\Middleware\AuthenticateSession::class,``` and the other is changing ```Route::middleware(['auth:sanctum', 'verified'])``` to ```Route::middleware(['auth:web', 'verified'])``` in my routes file. Does anyone know the implications of doing any of those options?

Thank you!

**Comment by MACscr** [comment] 2022-03-29 23:02
What error do you get in both the browser and error log when you try?

- Mark

**Comment by seabasss** [comment] 2022-03-29 23:07
No error. In Filament I go to users and then click the impersonate button and I just get logged out and end up on the Jetstream log in page. It used to work fine before I updated Laravel. It seems like the issues started around Laravel v9.5.0.

See possibly related issues:
https://github.com/404labfr/laravel-impersonate/issues/154
https://github.com/laravel/framework/pull/41447

**Comment by Wit3** [comment] 2022-08-05 10:46
> Is this still an issue?

yes!

**Comment by ziming** [comment] 2022-10-12 12:36
impersonate suddenly stopped working for me as well

**Comment by pschilly** [comment] 2022-11-25 13:42
Fresh install - also not working after following all directions to a T.

**Comment by timrey** [comment] 2022-12-14 16:25
Any news on this?

**Comment by jszobody** [comment] 2023-02-18 15:53
Is everyone using Sanctum in this thread?

I've been utterly unable to reproduce the issue myself. Fresh Laravel 10 app, fresh Filament install, and then installed this package `2.11` and it just works. I also went back and installed Jetstream with the livewire stack, and it also is working great.

I'm not seeing any issue with this package and latest versions of Laravel, at all.

Now there _might_ be something we need to look at with Sanctum specifically, not sure. A few in this thread mention Sanctum. I'm not terribly familiar with that. Can someone provide more specific instructions on how to reproduce this, with a fresh Laravel app, using Sanctum? 

If anyone else is still having problems with latest Laravel, please try to reproduce in a fresh app and provide details. If I can't reproduce, I can't see what the issue is and how to fix.

**Comment by jszobody** [comment] 2023-02-18 19:13
Alright, after a bunch of trial & error today I _think_ I was able to reproduce what y'all are seeing with Sanctum. And `2.12` has been tagged with a fix.

Ultimately the issue needs to be resolved in the underlying `404labfr/laravel-impersonate` package, they have multiple, lengthy tickets on this topic with currently no solution in place. I think my 2.12 update will work around the issue for now, please let me know if you still have problems logging out.

**Closed by jszobody** 2023-02-18 19:13 UTC
